export const ex1 = {
  results: [
    {
      "Product_Type": "Dataset",
      "Short_Name": "ARGO_BGC_Jun2023",
      "Long_Name": "Argo Float Biogeochemical Profiles - June 2023",
      "Dataset_Release_Date": "2023-06-10T00:00:00.000Z",
      "Dataset_History": "",
      "Dataset_Version": "Argo REP - 2023-06-10",
      "Table_Name": "tblArgoBGC_REP_Jun2023",
      "Process_Level": "Reprocessed",
      "Make": "Observation",
      "Data_Source": "http://www.argodatamgt.org/",
      "Distributor": "https://data-argo.ifremer.fr",
      "Dataset_ID": 601,
      "Spatial_Resolution": "Irregular",
      "Temporal_Resolution": "Irregular",
      "Study_Domain": "Biogeochemistry",
      "Lat_Min": -77.8054,
      "Lat_Max": 82.93,
      "Lon_Min": -179.996,
      "Lon_Max": 181.706,
      "Depth_Min": 0,
      "Depth_Max": 6404.3229735251,
      "Time_Min": "2002-09-08T23:02:51.000Z",
      "Time_Max": "2023-06-08T17:42:24.000Z",
      "Sensors": [
        "Backscatter Sensor",
        "Ultraviolet Absorbance Detector",
        "Radiometer",
        "CTD",
        "Uncategorized",
        "Optode",
        "Ion Sensitive Field Effect Transistor",
        "Turbidity Sensor"
      ],
      "Visualize": 1,
      "Row_Count": null,
      "Regions": null,
    },
    {
      "Product_Type": "Dataset",
      "Short_Name": "MV1015_cmore_bottle",
      "Long_Name": "C-MORE BiG-RAPA MV1015 Downcast Bottle Data",
      "Dataset_Release_Date": "2023-02-25T00:00:00.000Z",
      "Dataset_History": " ",
      "Dataset_Version": "final",
      "Table_Name": "tblMV1015_cmore_bottle",
      "Process_Level": "Reprocessed",
      "Make": "Observation",
      "Data_Source": "Dave Karl Lab, University of Hawaii at Manoa",
      "Distributor": "Center for Microbial Oceanography: Research & Education; Data System (cmoreDS), University of Hawaii",
      "Acknowledgement": "Center for Microbial Oceanography: Research and Education (C-MORE), and NSF",
      "Dataset_ID": 527,
      "Spatial_Resolution": "Irregular",
      "Temporal_Resolution": "Irregular",
      "Study_Domain": "Biology",
      "Lat_Min": -26.2486666667,
      "Lat_Max": -20.0821666667,
      "Lon_Min": -104.2543333333,
      "Lon_Max": -70.7996666667,
      "Depth_Min": 1.4902143371,
      "Depth_Max": 198.5997480785,
      "Time_Min": "2010-11-19T12:39:14.000Z",
      "Time_Max": "2010-12-12T03:30:19.000Z",
      "Sensors": [
        "CTD",
        "Uncategorized",
        "Winkler Titration",
        "Coulometer",
        "Potentiometric Titration",
        "Autoanalyzer",
        "Elemental Analyzer",
        "Spectrophotometer",
        "HPLC",
        "Flow Cytometer"
      ],
      "Visualize": 1,
      "Row_Count": 1184,
      "Regions": null,
    }
  ],
  storedOptions: {
    "Sensor": [],
    "Temporal_Resolution": [
      "Any"
    ],
    "Spatial_Resolution": [
      "Any"
    ],
    "Data_Source": [
      "Any"
    ],
    "Distributor": [
      "Any"
    ],
    "Process_Level": [
      "Any"
    ],
    "Make": [],
    "Region": []
  },
  params: {}
};

export const ex2 = {
  results: ex1.results,
  storedOptions: {
    "Temporal_Resolution": [
      "1/6 s",
      "10 Seconds",
      "30 seconds",
      "Any",
      "Daily",
      "Eight Day Running",
      "Eight Days",
      "Hourly",
      "Irregular",
      "Monthly",
      "Monthly Climatology",
      "One Minute",
      "One Second",
      "Six Hourly",
      "Three Days",
      "Three Minutes",
      "Three Seconds",
      "Weekly"
    ],
    "Spatial_Resolution": [
      "1/2° X 1/2°",
      "1/25° X 1/25°",
      "1/4° X 1/4°",
      "1/48° X 1/48°",
      "1/8° X 1/8°",
      "1° X 1°",
      "15 arc-second interval grid",
      "70km X 70km",
      "9km X 9km",
      "Any",
      "Irregular"
    ],
    "Data_Source": [
      "Angel White Lab, University of Hawaii at Manoa",
      "Angelique White, Scope-Gradients program, University of Hawaii, Manoa",
      "Anitra Ingalls Lab - University of Washington",
      "Any",
      "Armbrust Lab, University of Washington",
      "Atlantic Meridional Transect",
      "Atlantic Meridional Transect (AMT)",
      "Atlantic Meridional Transect (AMT), David Robins, Plymouth Marine Laboratory",
      "Atlantic Meridional Transect (AMT), Dr. Ray Barlow, Plymouth Marine Laboratory",
      "Atlantic Meridional Transect (AMT), Dr. Tony Bale, Plymouth Marine Laboratory",
      "Atlantic Meridional Transect (AMT), Malcolm Woodward, Plymouth Marine Laboratory",
      "Atlantic Meridional Transect (AMT), Tony Bale, Plymouth Marine Laboratory",
      "AVISO+",
      "Bermuda Institute of Ocean Sciences",
      "Bess Ward lab Princeton University, Andrew E Allen J. Craig Venter Institute (JCVI), Daniel M Sigman Princeton University, Dimensions of Biodiversity (DimBio NABE).",
      "Bonnet lab, Aix Marseille Université, Marseille, France",
      "Bundy lab, University of Washington",
      "Bundy Lab, University of Washington",
      "C-MORE, Chisholm Lab",
      "Cheung Lab, The Hong Kong University of Science and Technology, Hong Kong, China",
      "Chisholm Lab, Massachusettes Institute of Technology",
      "Chisolm Lab - DOI: 10.1038/sdata.2018.154",
      "Church lab, University of Montana",
      "Clivar & Carbon Hydrographic Data Office (CCHDO) at University of California San Diego (UCSD)",
      "CMEMS - Global Monitoring and Forecasting Centre",
      "Coccolithophores of the Patagonian Shelf 2008 (COPAS08) -  Ocean Carbon and Biogeochemistry (OCB)",
      "Copernicus-GlobColour",
      "Dalhousie University Finkel/Irwin Lab",
      "Dave Karl Lab, University of Hawaii at Manoa",
      "Dave Karl, University of Hawaii, Manoa",
      "David A. Caron",
      "David A. Caron, USC",
      "DeLong lab, University of Hawaii, Manoa",
      "Dyhrman/LDEO",
      "Edward DeLong Lab at University of Hawaii, Manoa",
      "Erik Buitenhuis, University of East Anglia",
      "Follows Group, Massachusetts Institute of Technology",
      "Fuhrman Lab, University of Southern California",
      "GLOBAL_ANALYSIS_FORECAST_BIO_001_014_TDS",
      "GO-SHIP IO9, Bigelow Laboratory for Ocean Sciences, Lomas Lab",
      "Hawaii Ocean Time-series (HOT)",
      "Hawaii Ocean Time-series (HOT), Dave Karl",
      "http://darwinproject.mit.edu",
      "http://doi.org/10.7289/V5NZ85MT",
      "http://mixedlayer.ucsd.edu/",
      "http://oceandata.sci.gsfc.nasa.gov",
      "http://scope.soest.hawaii.edu/data/gradients/data/",
      "http://www.argodatamgt.org/",
      "https://data.marine.copernicus.eu/product/SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046",
      "https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.nodc:AOML-GDP#",
      "https://doi.org/10.5067/PRESW-ASJ10",
      "https://doi.org/10.7289/v5kw5d97, doi: https://doi.org/10.5194/essd-8-297-2016, https://doi.org/10.5194/essd-2019-66",
      "https://oceandata.sci.gsfc.nasa.gov/",
      "https://resources.marine.copernicus.eu/product-detail/SEALEVEL_GLO_PHY_L4_MY_008_047/INFORMATION",
      "https://www.bodc.ac.uk/data/documents/cruise/11427/",
      "https://www.bodc.ac.uk/geotraces/data/idp2021/",
      "https://www.ncei.noaa.gov/data/oceans/ncei/woa/",
      "https://www.socat.info/",
      "IFREMER CERSAT",
      "Ingalls Lab - University of Washington",
      "Ingalls Lab, University of Washington",
      "John Lab USC",
      "John Lab, University of Southern California",
      "Juranek Lab, Oregon State University",
      "Karl lab, University of Hawaii at Manoa",
      "LAADS DAAC - Goddard Space Flight Center - NASA",
      "Lindell lab - Technion, Haifa, Israel",
      "Marine Biological Association",
      "Marine Chemistry Laboratory- University of Washington",
      "Matthew  Church, Univ Montana",
      "Matthew  Church, University Montana",
      "Matthew Church, Univ Montana",
      "Matthew Church, University of Hawaii",
      "MERCATOR BIOMER4V1R2",
      "Michael R Landry lab University of California-San Diego (UCSD SIO) Costa Rica Dome FLUx and Zinc Experiments Integrated Marine Biogeochemistry and Ecosystem Research US and Ocean Carbon and Biogeochemistry",
      "Moisander lab, University of Massachusetts Dartmouth",
      "NASA JPL - PODAAC",
      "National Centers for Environmental Information",
      "NCEI, NOAA, https://experience.arcgis.com/experience/b296879cc1984fda833a8acc93e31476",
      "Ocean Biology Processing Group at NASA GSFC",
      "Opedia, Mohammad D. Ashkezari",
      "Pedro Flombaum (pflombaum@cima.fcen.uba.ar)",
      "Plymouth Marine Laboratory, NERC, Chisholm Lab",
      "Remote Sensing Systems, Santa Rosa, CA, USA  http://www.remss.com/missions/smap/",
      "Repeta Lab- Woods Hole Oceanographic Institution",
      "Repeta lab, Woods Hole Oceanographic Institution",
      "Ricardo Letelier Lab, Oregon State University (OSU-CEOAS)",
      "Robert R. Bidigare, University of Hawaii at Manoa (SOEST)",
      "Sallie W. Chisholm and Paul Berube Labs, Massachusetts Institute of Technology (MIT)",
      "Sam Wilson, Steve Poulos, and Dave Karl, University of Hawaii, Manoa",
      "School of Ocean and Earth Science and Technology at the University of Hawaii at Manoa",
      "SCOPE Core / Processed by the lab of Ginger Armbrust - University of Washington",
      "Seabed2030 https://seabed2030.org/",
      "SeaFlow@UW, University of Washington, https://seaflow.netlify.app/",
      "Shiozaki Lab, The University of Tokyo, Kashiwa, Japan",
      "SOCAT (SurfaceOcean CO2 Atlas); https://www.socat.info/",
      "Solange Duhamel lab Lamont-Doherty Earth Observatory (LDEO), Oligotrophy to UlTra-oligotrophy PACific Experiment (OUTPACE)\\t",
      "Sonya Dyhrman - Columbia University",
      "Sonya Dyhrman, LDEO/Columbia Univ.",
      "Sunagawa, Coelho, Chaffron, et al., Science, 2015",
      "Tara Oceans Foundation",
      "University of Hawaii - Manoa, David Karl lab",
      "University of Hawaii - Manoa, David Karl lab, dkarl@hawaii.edu, sferron@hawaii.edu",
      "University of Hawaii, Manoa",
      "University of Hawaii, Manoa, Karl Lab",
      "University of Washington",
      "White lab - University of Hawaii",
      "White Lab - University of Hawaii at Manoa",
      "Zehr Lab at UCSC",
      "Zehr lab, University of California Santa Cruz"
    ],
    "Distributor": [
      "Angel White Lab, University of Hawaii at Manoa",
      "Any",
      "Armbrust Lab, University of Washington",
      "AVISO+",
      "BCO-DMO",
      "Bermuda Institute of Ocean Sciences",
      "Biological and Chemical Oceanography Data Management Office (BCO-DMO)",
      "British Oceanographic Data Centre (BODC)",
      "British Oceanography Data Centre - National Oceanography Centre",
      "Caron lab, University of Southern California",
      "Center for Microbial Oceanography: Research & Education; Data System (cmoreDS), University of Hawaii",
      "CMAP",
      "Dave Karl Lab - University of Hawaii - Manoa",
      "Dave Karl Lab, University of Hawaii at Manoa",
      "DeLong lab, University of Hawaii, Manoa",
      "Follows Group, Massachusetts Institute of Technology",
      "GEOTRACES International Data Assembly Centre",
      "http://darwinproject.mit.edu",
      "http://doi.org/10.5281/zenodo.2678021",
      "http://hahana.soest.hawaii.edu/hot/hot-dogs/",
      "http://marine.copernicus.eu",
      "http://marine.copernicus.eu/",
      "http://mixedlayer.ucsd.edu/",
      "https://chisholmlab.mit.edu/",
      "https://data-argo.ifremer.fr",
      "https://data.remss.com/smap/SSS/V05.0/FINAL/L3/8day_running",
      "https://doi.pangaea.de/10.1594/PANGAEA.777385",
      "https://hahana.soest.hawaii.edu/cmorebula/cmorebula.html",
      "https://hahana.soest.hawaii.edu/cmoreserver/datasearch/data.php",
      "https://ladsweb.nascom.nasa.gov/",
      "https://marine.copernicus.eu/",
      "https://podaac-opendap.jpl.nasa.gov/opendap/SalinityDensity/smap/L3/RSS/V4/8day_running/SCI",
      "https://podaac.jpl.nasa.gov/",
      "https://www.gebco.net",
      "https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:NCEI-WOA18",
      "https://www.nodc.noaa.gov/OC5/woa13/",
      "https://www.socat.info/index.php/data-access/",
      "Ingalls Lab - University of Washington",
      "Ingalls Lab, University of Washington",
      "John Lab - USC",
      "John Lab, University of Southern California",
      "Jon Zehr Lab",
      "Karl lab, University of Hawaii at Manoa",
      "Marine Biological Association",
      "Matthew  Church, Univ Montana",
      "Matthew  Church, University Montana",
      "Matthew Church, Univ Montana",
      "NASA JPL - PODAAC",
      "National Oceanic and Atmospheric Administration Atlantic Oceanography and Meteorological Laboratory",
      "NCBI, https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA596510",
      "NCBI, https://www.ncbi.nlm.nih.gov/bioproject/PRJNA596510",
      "NCBI, https://www.ncbi.nlm.nih.gov/bioproject/PRJNA707586",
      "NCEI, NOAA",
      "NOAA - https://www.nodc.noaa.gov/ocads/oceans/glodap/GlopDV.html",
      "Ocean Biology Processing Group at NASA GSFC",
      "Pangaea - Data Publisher for Earth & Environmental Science",
      "Pedro Flombaum (pflombaum@cima.fcen.uba.ar)",
      "Repeta Lab- Woods Hole Oceanographic Institution",
      "School of Ocean and Earth Science and Technology at the University of Hawaii at Manoa FTP Site.",
      "SCOPE core / Armbrust lab - University of Washington",
      "Simons CMAP, University of Washington",
      "Sonya Dyhrman - Columbia University",
      "Tara Oceans: https://www.embl.org/topics/tara/",
      "University of Hawaii - Manoa, David Karl lab",
      "University of Hawaii, Manoa",
      "University of Hawaii, Manoa, Karl Lab",
      "University of Southern California",
      "White lab - University of Hawaii",
      "Zehr Lab at UCSC",
      "Zehr Lab UCSC",
      "Zehr lab, University of California Santa Cruz",
      "Zehr Lab, University of California Santa Cruz"
    ],
    "Process_Level": [
      "Any",
      "Near-Real-Time",
      "Reprocessed"
    ],
    "Make": [
      "Model",
      "Observation"
    ],
    "Sensor": [
      "Anemometer",
      "Aquatic Laser Fluorescence Analyzer",
      "ATP photometer",
      "Autoanalyzer",
      "Backscatter Sensor",
      "Barometer",
      "Biospherical QSR 2150A",
      "Blend",
      "Bottle",
      "Calorimeter",
      "Chemiluminescent Analyzer",
      "Colorimeter",
      "Colorimiter",
      "Coulometer",
      "CPR",
      "CTD",
      "Drifter",
      "Electron Capture Detector",
      "Elemental Analyzer",
      "Epifluorescent Microscope",
      "Flame Ionization Detector",
      "Flow Cytobot",
      "Flow Cytometer",
      "Flow Cytometer and Microscope",
      "FlowCam",
      "Fluorogenic Substrate",
      "fluorometer",
      "GPS",
      "Gyrocompass",
      "High Temperature Combustion",
      "High Throughput Sequencer",
      "HPLC",
      "Hyperpro",
      "ICP-MS",
      "In-Situ",
      "Incubation",
      "Ion Sensitive Field Effect Transistor",
      "Liquid Chromatograph",
      "Liquid Scintillation Counter",
      "LISST",
      "Mass Spectrometer",
      "Optical",
      "Optode",
      "pH Sensor",
      "Potentiometric Electrode",
      "Potentiometric Titration",
      "Pyranometer",
      "qPCR",
      "Radiometer",
      "Salinometer",
      "Satellite",
      "Scatterometer",
      "SeaFlow",
      "Seaglider",
      "Sediment Trap",
      "Spectral Backscattering Sensor",
      "Spectrophotometer",
      "Temperature Sensor",
      "Thermosalinograph",
      "Titration",
      "Towfish",
      "Turbidity Sensor",
      "Ultraviolet Absorbance Detector",
      "Uncategorized",
      "Underway CTD",
      "Underway pCO2 Sensor",
      "Winkler Titration",
      "Zooplankton Net"
    ],
    "Region": [
      "Arctic Ocean",
      "Caribbean Sea",
      "Global",
      "Gulf of Mexico",
      "Indian Ocean",
      "Mediterranean Sea",
      "North Atlantic Ocean",
      "North Pacific Ocean",
      "South Atlantic Ocean",
      "South Pacific Ocean",
      "Southern Ocean"
    ]
  },
  params: {
    "hasDepth": "any",
    "keywords": "oxygen",
    "latEnd": "90",
    "latStart": "-90",
    "lonEnd": "180",
    "lonStart": "-180",
    "timeEnd": "2023-08-02",
    "timeStart": "1900-01-01"
  }
}

export const ex3 = {
  results: ex1.results,
  storedOptions: ex1.storedOptions,
  params: {
    ...ex2.params,
    sensor: 'CTD'
  }
}
