export const GeographicBoundaries = Object.freeze([
  {
    label: 'BATS Region',
    southLatitude: 30.758824,
    northLatitude: 32.743847,
    westLongitude: -65.166799,
    eastLongitude: -63.1667,
  },
  {
    label: 'Global',
    southLatitude: -90,
    northLatitude: 90,
    westLongitude: -180,
    eastLongitude: 180,
  },
  {
    label: 'Southern Ocean',
    southLatitude: -90,
    northLatitude: -60,
    westLongitude: -180,
    eastLongitude: 180,
  },
  {
    label: 'Arctic Ocean',
    southLatitude: 60,
    northLatitude: 90,
    westLongitude: -180,
    eastLongitude: 180,
  },
  {
    label: 'Atlantic Ocean',
    southLatitude: -90,
    northLatitude: 90,
    westLongitude: -83,
    eastLongitude: 14,
  },
  {
    label: 'Northern Atlantic Ocean',
    southLatitude: 0,
    northLatitude: 90,
    westLongitude: -83,
    eastLongitude: 14,
  },
  {
    label: 'Southern Atlantic Ocean',
    southLatitude: -90,
    northLatitude: 0,
    westLongitude: -83,
    eastLongitude: 14,
  },
  {
    label: 'Pacific Ocean',
    southLatitude: -90,
    northLatitude: 65,
    westLongitude: 146,
    eastLongitude: -70,
  },
  {
    label: 'Northern Pacific Ocean',
    southLatitude: 0,
    northLatitude: 90,
    westLongitude: 146,
    eastLongitude: -70,
  },
  {
    label: 'Southern Pacific Ocean',
    southLatitude: -90,
    northLatitude: 0,
    westLongitude: 146,
    eastLongitude: -70,
  },
  {
    label: 'Indian Ocean',
    southLatitude: -90,
    northLatitude: 30,
    westLongitude: 14,
    eastLongitude: 147,
  },
  {
    label: 'Mediterranean Sea',
    southLatitude: 30,
    northLatitude: 46,
    westLongitude: -6,
    eastLongitude: 37,
  },
  {
    label: 'Gulf of Mexico',
    southLatitude: 18,
    northLatitude: 31,
    westLongitude: -99,
    eastLongitude: -80,
  },
]);
