export const GeographicBoundaries = Object.freeze([
  {
    label: 'Global',
    northLatitude: 90,
    southLatitude: -90,
    eastLongitude: 180,
    westLongitude: -180,
  },
  {
    label: 'Southern Ocean',
    northLatitude: -60,
    southLatitude: -90,
    eastLongitude: 180,
    westLongitude: -180,
  },
  {
    label: 'Arctic Ocean',
    northLatitude: 90,
    southLatitude: 60,
    eastLongitude: 180,
    westLongitude: -180,
  },
  {
    label: 'Atlantic Ocean',
    northLatitude: 90,
    southLatitude: -90,
    eastLongitude: 14,
    westLongitude: -83,
  },
  {
    label: 'Northern Atlantic Ocean',
    northLatitude: 90,
    southLatitude: 0,
    eastLongitude: 14,
    westLongitude: -83,
  },
  {
    label: 'Southern Atlantic Ocean',
    northLatitude: 0,
    southLatitude: -90,
    eastLongitude: 14,
    westLongitude: -83,
  },
  {
    label: 'Pacific Ocean',
    northLatitude: 65,
    southLatitude: -90,
    eastLongitude: -70,
    westLongitude: 146,
  },
  {
    label: 'Northern Pacific Ocean',
    northLatitude: 90,
    southLatitude: 0,
    eastLongitude: -70,
    westLongitude: 146,
  },
  {
    label: 'Southern Pacific Ocean',
    northLatitude: 0,
    southLatitude: -90,
    eastLongitude: -70,
    westLongitude: 146,
  },
  {
    label: 'Indian Ocean',
    northLatitude: 30,
    southLatitude: -90,
    eastLongitude: 147,
    westLongitude: 14,
  },
  {
    label: 'Mediterranean Sea',
    northLatitude: 46,
    southLatitude: 30,
    eastLongitude: 37,
    westLongitude: -6,
  },
  {
    label: 'Gulf of Mexico',
    northLatitude: 31,
    southLatitude: 18,
    eastLongitude: -80,
    westLongitude: -99,
  },
  {
    label: 'BATS Region',
    northLatitude: 32.743847,
    southLatitude: 30.758824,
    eastLongitude: -63.1667,
    westLongitude: -65.166799,
  },
]);
