export const GeographicBoundaries = Object.freeze([
  {
    label: 'BATS Region',
    southLatitude: 30.758824,
    northLatitude: 32.743847,
    westLongitude: -65.166799,
    eastLongitude: -63.1667,
  },
  {
    label: 'Global',
    southLatitude: -90,
    northLatitude: 90,
    westLongitude: -180,
    eastLongitude: 180,
  },
  {
    label: 'Southern Ocean',
    southLatitude: -90,
    northLatitude: -60,
    westLongitude: -180,
    eastLongitude: 180,
  },
  {
    label: 'Arctic Ocean',
    southLatitude: 66,
    northLatitude: 90,
    westLongitude: -180,
    eastLongitude: 180,
  },
  {
    label: 'Northern Atlantic Ocean',
    southLatitude: 0,
    northLatitude: 60,
    westLongitude: -76,
    eastLongitude: -6,
  },
  {
    label: 'Southern Atlantic Ocean',
    southLatitude: -60,
    northLatitude: 0,
    westLongitude: -68,
    eastLongitude: 20,
  },
  {
    label: 'Northern Pacific Ocean',
    southLatitude: 0,
    northLatitude: 66,
    westLongitude: 120,
    eastLongitude: -98,
  },
  {
    label: 'Southern Pacific Ocean',
    southLatitude: -60,
    northLatitude: 0,
    westLongitude: 147,
    eastLongitude: -68,
  },
  {
    label: 'Indian Ocean',
    southLatitude: -60,
    northLatitude: 30,
    westLongitude: 20,
    eastLongitude: 120,
  },
  {
    label: 'Mediterranean Sea',
    southLatitude: 31,
    northLatitude: 45,
    westLongitude: -1,
    eastLongitude: 36,
  },
  {
    label: 'Gulf of Mexico',
    southLatitude: 20,
    northLatitude: 30,
    westLongitude: -97,
    eastLongitude: -83,
  },
]);
