// Dataset download request actions
export const DATASET_DOWNLOAD_REQUEST_SEND = 'DATASET_DOWNLOAD_REQUEST_SEND';
export const DATASET_DOWNLOAD_REQUEST_SUCCESS =
  'DATASET_DOWNLOAD_REQUEST_SUCCESS';
export const DATASET_DOWNLOAD_REQUEST_FAILURE =
  'DATASET_DOWNLOAD_REQUEST_FAILURE';
export const DATASET_DOWNLOAD_REQUEST_PROCESSING =
  'DATASET_DOWNLOAD_REQUEST_PROCESSING';

// Query size check actions
export const CHECK_QUERY_SIZE_SEND = 'CHECK_QUERY_SIZE_SEND';
export const SET_CHECK_QUERY_SIZE_REQUEST_STATE = 'SET_CHECK_QUERY_SIZE_STATE';
export const STORE_CHECK_QUERY_SIZE_RESULT = 'STORE_CHECK_QUERY_SIZE_RESULT';
export const CLEAR_FAILED_SIZE_CHECKS = 'CLEAR_FAILED_SIZE_CHECKS';

// Vault link actions
export const FETCH_VAULT_LINK = 'FETCH_VAULT_LINK';
export const FETCH_VAULT_LINK_SUCCESS = 'FETCH_VAULT_LINK_SUCCESS';
export const SET_FETCH_VAULT_LINK_REQUEST_STATUS =
  'SET_FETCH_VAULT_LINK_REQUEST_STATUS';

// Dropbox modal actions
export const DROPBOX_MODAL_OPEN = 'DROPBOX_MODAL_OPEN';
export const DROPBOX_MODAL_CLEANUP = 'DROPBOX_MODAL_CLEANUP';
export const DROPBOX_MODAL_CLOSE = 'DROPBOX_MODAL_CLOSE';
