/**
 * Ground Truth Tests for Row Count Estimation
 *
 * These tests use actual row counts from SQL Server to validate
 * the estimateRowCount function against real data.
 *
 * Ground truth data is generated by:
 *   node endpointTester/tests/estimation/gather-ground-truth.js
 *
 * Test approach:
 * - Mock query functions with actual SQLite values from catalog.db
 * - Compare estimated row count against actual row count from SQL Server
 * - Log the ratio to analyze if the 1.4x multiplier is correct
 */

import estimateRowCountForDataset from '../estimateRowCountForDataset';
import * as queryTables from '../queryEstimationTables';
import groundTruth from './groundTruth.json';

// Mock the query functions
jest.mock('../queryEstimationTables');

/**
 * Build dataset metadata object from test case
 */
function buildDatasetMetadata(testCase) {
  return {
    shortName: testCase.dataset.tableName,
    tableName: testCase.dataset.tableName,
    spatialResolution: testCase.dataset.spatialResolution,
    temporalResolution: testCase.dataset.temporalResolution,
    hasDepth: Boolean(testCase.sqliteValues.depthModel),
  };
}

/**
 * Build constraints object from test case
 */
function buildConstraints(testCase) {
  const constraints = {
    spatialBounds: {
      latMin: testCase.constraints.spatial.latMin,
      latMax: testCase.constraints.spatial.latMax,
      lonMin: testCase.constraints.spatial.lonMin,
      lonMax: testCase.constraints.spatial.lonMax,
    },
    temporalEnabled: Boolean(testCase.constraints.temporal),
    temporalRange: {
      timeMin: testCase.constraints.temporal
        ? `${testCase.constraints.temporal.startDate}T00:00:00Z`
        : null,
      timeMax: testCase.constraints.temporal
        ? `${testCase.constraints.temporal.endDate}T00:00:00Z`
        : null,
    },
    depthEnabled: Boolean(testCase.constraints.depth),
    depthRange: {
      depthMin: testCase.constraints.depth
        ? testCase.constraints.depth.depthMin
        : null,
      depthMax: testCase.constraints.depth
        ? testCase.constraints.depth.depthMax
        : null,
    },
  };

  return constraints;
}

describe('estimateRowCount - Ground Truth Validation', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  groundTruth.testCases.forEach((testCase) => {
    it(`${testCase.name}: compare estimated vs actual row count`, async () => {
      // Configure mocks with real SQLite values
      queryTables.querySpatialResolutionMapping.mockResolvedValue({
        value: testCase.sqliteValues.spatialResolutionValue,
        units: 'degrees',
      });

      queryTables.queryTemporalResolutionMapping.mockResolvedValue({
        value: testCase.sqliteValues.temporalResolutionValue,
        units: 'seconds',
      });

      // Configure depth mocks if applicable
      if (testCase.sqliteValues.depthModel) {
        queryTables.queryDatasetDepthModel.mockResolvedValue(
          testCase.sqliteValues.depthModel
        );

        // queryDepthCount called twice: total levels, then constrained range
        queryTables.queryDepthCount
          .mockResolvedValueOnce(testCase.sqliteValues.depthCount || 1)
          .mockResolvedValueOnce(testCase.sqliteValues.depthCount || 1);
      }

      const datasetMetadata = buildDatasetMetadata(testCase);
      const constraints = buildConstraints(testCase);
      const mockDb = {};

      // Run estimation
      const result = await estimateRowCountForDataset(
        datasetMetadata,
        constraints,
        mockDb
      );

      if (!result.eligible) {
        console.log(`${testCase.name}: ineligible - ${result.reason}`);
        return;
      }

      const estimated = result.rowCount;

      // Calculate ratio for analysis
      const ratio = estimated / testCase.actualRowCount;

      // Log comparison for analysis
      console.log(
        `${testCase.name}: estimated=${Math.round(estimated)}, actual=${testCase.actualRowCount}, ratio=${ratio.toFixed(2)}`
      );

      // For now, just log the results - we'll analyze and adjust expectations
      // after seeing the actual ratios
      expect(estimated).toBeGreaterThan(0);
      expect(testCase.actualRowCount).toBeGreaterThan(0);
    });
  });
});
