export const RETRIEVAL_REQUEST_SEND = 'CATALOG_RETRIEVAL_REQUEST_SEND';
export const RETRIEVAL_REQUEST_SUCCESS = 'CATALOG_RETRIEVAL_REQUEST_SUCCESS';
export const RETRIEVAL_REQUEST_FAILURE = 'CATALOG_RETRIEVAL_REQUEST_FAILURE';
export const RETRIEVAL_REQUEST_PROCESSING = 'CATALOG_RETRIEVAL_REQUEST_PROCESSING';

export const DATASET_RETRIEVAL_REQUEST_SEND = 'DATASET_CATALOG_RETRIEVAL_REQUEST_SEND';
export const DATASET_RETRIEVAL_REQUEST_SUCCESS = 'DATASET_CATALOG_RETRIEVAL_REQUEST_SUCCESS';
export const DATASET_RETRIEVAL_REQUEST_FAILURE = 'DATASET_CATALOG_RETRIEVAL_REQUEST_FAILURE';
export const DATASET_RETRIEVAL_REQUEST_PROCESSING = 'DATASET_CATALOG_RETRIEVAL_REQUEST_PROCESSING';

export const SUBMISSION_OPTIONS_RETRIEVAL = 'SUBMISSION_OPTIONS_RETRIEVAL';
export const STORE_SUBMISSION_OPTIONS = 'STORE_SUBMISSION_OPTIONS';

export const KEYWORDS_FETCH = 'KEYWORDS_FETCH';
export const KEYWORDS_STORE = 'KEYWORDS_STORE';

export const SEARCH_OPTIONS_FETCH = 'SEARCH_OPTIONS_FETCH';
export const SEARCH_OPTIONS_STORE = 'SEARCH_OPTIONS_STORE';

export const SEARCH_RESULTS_FETCH = 'SEARCH_RESULTS_FETCH';
export const SEARCH_RESULTS_STORE = 'SEARCH_RESULTS_STORE';
export const SEARCH_RESULTS_SET_LOADING_STATE = 'SEARCH_RESULTS_SET_LOADING_STATE';

export const DATASET_FULL_PAGE_DATA_FETCH = 'DATASET_FULL_PAGE_DATA_FETCH';
export const DATASET_FULL_PAGE_DATA_STORE = 'DATASET_FULL_PAGE_DATA_STORE';
export const DATASET_FULL_PAGE_DATA_SET_LOADING_STATE = 'DATASET_FULL_PAGE_DATA_SET_LOADING_STATE';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_CLEAR = 'CART_CLEAR';
export const CART_ADD_MULTIPLE = 'CART_ADD_MULTIPLE';