// Download actions
export const DOWNLOAD_DROPBOX_VAULT_FILES_REQUEST =
  'DOWNLOAD_DROPBOX_VAULT_FILES_REQUEST';
export const DOWNLOAD_DROPBOX_VAULT_FILES_SUCCESS =
  'DOWNLOAD_DROPBOX_VAULT_FILES_SUCCESS';
export const DOWNLOAD_DROPBOX_VAULT_FILES_FAILURE =
  'DOWNLOAD_DROPBOX_VAULT_FILES_FAILURE';
export const DOWNLOAD_DROPBOX_VAULT_FILES_CLEAR =
  'DOWNLOAD_DROPBOX_VAULT_FILES_CLEAR';

// Vault files pagination actions
export const FETCH_DROPBOX_VAULT_FILES_PAGE = 'FETCH_DROPBOX_VAULT_FILES_PAGE';
export const FETCH_DROPBOX_VAULT_FILES_PAGE_SUCCESS =
  'FETCH_DROPBOX_VAULT_FILES_PAGE_SUCCESS';
export const FETCH_DROPBOX_VAULT_FILES_PAGE_FAILURE =
  'FETCH_DROPBOX_VAULT_FILES_PAGE_FAILURE';
export const SET_DROPBOX_VAULT_FILES_PAGINATION =
  'SET_DROPBOX_VAULT_FILES_PAGINATION';
export const RESET_DROPBOX_VAULT_FILES_PAGINATION =
  'RESET_DROPBOX_VAULT_FILES_PAGINATION';
