export const DROPBOX_FILES_DOWNLOAD_REQUEST = 'DROPBOX_FILES_DOWNLOAD_REQUEST';
export const DROPBOX_FILES_DOWNLOAD_SUCCESS = 'DROPBOX_FILES_DOWNLOAD_SUCCESS';
export const DROPBOX_FILES_DOWNLOAD_FAILURE = 'DROPBOX_FILES_DOWNLOAD_FAILURE';
export const DROPBOX_FILES_DOWNLOAD_CLEAR = 'DROPBOX_FILES_DOWNLOAD_CLEAR';

// Vault files pagination actions
export const FETCH_VAULT_FILES_PAGE = 'FETCH_VAULT_FILES_PAGE';
export const FETCH_VAULT_FILES_PAGE_SUCCESS = 'FETCH_VAULT_FILES_PAGE_SUCCESS';
export const FETCH_VAULT_FILES_PAGE_FAILURE = 'FETCH_VAULT_FILES_PAGE_FAILURE';
export const SET_VAULT_FILES_PAGINATION = 'SET_VAULT_FILES_PAGINATION';
export const RESET_VAULT_FILES_PAGINATION = 'RESET_VAULT_FILES_PAGINATION';
