export const INTERFACE_SHOW_LOGIN_DIALOG = "INTERFACE_SHOW_LOGIN_DIALOG";
export const INTERFACE_HIDE_LOGIN_DIALOG = "INTERFACE_HIDE_LOGIN_DIALOG";

export const REGISTRATION_NEXT_ACTIVE_STEP = 'REGISTRATION_NEXT_ACTIVE_STEP';
export const REGISTRATION_PREVIOUS_ACTIVE_STEP = 'REGISTRATION_PREVIOUS_ACTIVE_STEP';

export const RESTORE_INTERFACE_DEFAULTS = 'RESTORE_INTERFACE_DEFAULTS';

export const SNACKBAR_OPEN = 'SNACKBAR_OPEN';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';