export const LOG_OUT = "LOG_OUT";

export const STORE_INFO = 'STORE_INFO';
export const DESTROY_INFO = 'DESTROY_INFO';
export const LOGIN_DIALOG_WAS_CLEARED = 'LOGIN_DIALOG_WAS_CLEARED'

export const LOGIN_REQUEST_SEND = 'LOGIN_REQUEST_SEND';
export const LOGIN_REQUEST_PROCESSING = 'LOGIN_REQUEST_PROCESSING';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
export const LOGIN_REQUEST_CLEAR_ERROR = 'LOGIN_REQUEST_CLEAR_ERROR';

export const REGISTRATION_REQUEST_SEND = 'REGISTRATION_REQUEST_SEND';
export const REGISTRATION_REQUEST_PROCESSING = 'REGISTRATION_REQUEST_PROCESSING';
export const REGISTRATION_REQUEST_SUCCESS = 'REGISTRATION_REQUEST_SUCCESS';
export const REGISTRATION_REQUEST_FAILURE = 'REGISTRATION_REQUEST_FAILURE';

export const VALIDATION_REQUEST_SEND = 'VALIDATION_REQUEST_SEND';
export const VALIDATION_REQUEST_PROCESSING = 'VALIDATION_REQUEST_PROCESSING';
export const VALIDATION_REQUEST_SUCCESS = 'VALIDATION_REQUEST_SUCCESS';
export const VALIDATION_REQUEST_FAILURE = 'VALIDATION_REQUEST_FAILURE';

export const KEY_RETRIEVAL_REQUEST_SEND = 'KEY_RETRIEVAL_REQUEST_SEND';
export const KEY_RETRIEVAL_REQUEST_SUCCESS = 'KEY_RETRIEVAL_REQUEST_SUCCESS';
export const KEY_RETRIEVAL_REQUEST_FAILURE = 'KEY_RETRIEVAL_REQUEST_FAILURE';

export const KEY_CREATION_REQUEST_SEND = 'KEY_CREATION_REQUEST_SEND';
export const KEY_CREATION_REQUEST_PROCESSING = 'KEY_CREATION_REQUEST_PROCESSING';
export const KEY_CREATION_REQUEST_SUCCESS = 'KEY_CREATION_REQUEST_SUCCESS';
export const KEY_CREATION_REQUEST_FAILURE = 'KEY_CREATION_REQUEST_FAILURE';