export const QUERY_REQUEST_SEND = 'QUERY REQUEST SEND';
export const QUERY_REQUEST_SUCCESS = 'QUERY REQUEST SUCCESS';
export const QUERY_REQUEST_FAILURE = 'QUERY REQUEST FAILURE';
export const QUERY_REQUEST_PROCESSING = 'QUERY REQUEST PROCESSING';

export const STORED_PROCEDURE_REQUEST_SEND = 'STORED_PROCEDURE_REQUEST_SEND';
export const STORED_PROCEDURE_REQUEST_SUCCESS = 'STORED_PROCEDURE_REQUEST_SUCCESS';
export const STORED_PROCEDURE_REQUEST_FAILURE = 'STORED_PROCEDURE_REQUEST_FAILURE';
export const STORED_PROCEDURE_REQUEST_PROCESSING = 'STORED_PROCEDURE_REQUEST_PROCESSING';

export const ADD_MAP = 'ADD_MAP';
export const ADD_CHART = 'ADD_CHART';

export const ADD_LAYER = 'ADD_LAYER';

export const STORE_SAMPLE_DATA = 'STORE_SAMPLE_DATA';

export const CLEAR_CHARTS = 'CLEAR_CHARTS';
export const CLEAR_MAPS = 'CLEAR_MAPS';

export const GET_TABLE_STATS = 'GET_TABLE_STATS';
export const GET_TABLE_STATS_REQUEST_PROCESSING = 'GET_TABLE_STATS_REQUEST_PROCESSING';
export const STORE_TABLE_STATS = 'STORE_TABLE_STATS';

export const CRUISE_TRAJECTORY_REQUEST_SEND = 'CRUISE_TRAJECTORY_REQUEST_SEND';
export const CRUISE_TRAJECTORY_REQUEST_SUCCESS = 'CRUISE_TRAJECTORY_REQUEST_SUCCESS';
export const CRUISE_TRAJECTORY_REQUEST_FAILURE = 'CRUISE_TRAJECTORY_REQUEST_FAILURE';
export const CRUISE_TRAJECTORY_REQUEST_PROCESSING = 'CRUISE_TRAJECTORY_REQUEST_PROCESSING';
export const CRUISE_TRAJECTORY_CLEAR = 'CRUISE_TRAJECTORY_CLEAR';

export const CRUISE_LIST_REQUEST_SEND = 'CRUISE_LIST_REQUEST_SEND';
export const CRUISE_LIST_REQUEST_SUCCESS = 'CRUISE_LIST_REQUEST_SUCCESS';
export const CRUISE_LIST_REQUEST_FAILURE = 'CRUISE_LIST_REQUEST_FAILURE';
export const CRUISE_LIST_REQUEST_PROCESSING = 'CRUISE_LIST_REQUEST_PROCESSING';

export const TRIGGER_SHOW_CHARTS = 'TRIGGER_SHOW_CHARTS';
export const COMPLETED_SHOW_CHARTS = 'COMPLETED_SHOW_CHARTS';